export const metadata = {
  title: 'I-Tech: Profil',
  description: 'Generated by create next app',
}

export default function Profil() {
  return (
    <main >
      <div >
        <p>Profil Page</p>
      </div>
    </main>
  )
}