export const metadata = {
  title: 'I-Tech: Berita Dan Pengumuman',
  description: 'Generated by create next app'
}

export default function Page() {
  return (
    <div >
      <div >
        <p>Berita Dan Pengumuman Page</p>
      </div>
    </div>
  )
}