export const metadata = {
  title: 'I-Tech: Tentang I-Tech',
  description: 'Generated by create next app'
}

export default function Page() {
  return (
    <div >
      <div >
        <p>Tentang I-Tech Page</p>
      </div>
    </div>
  )
}