export const metadata = {
  title: 'I-Tech: Akademik',
  description: 'Generated by create next app'
}

export default function Page() {
  return (
    <section className="container">

    </section >
  )
}