import './globals.css';
import Navigation from './components/Navigation';

export const metadata = {
  title: 'I-Tech',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="id">
      <body>
        <Navigation></Navigation>
        {children}
      </body>
    </html>
  )
}
