import './reset.css';
import './globals.css';
import { Nunito_Sans } from 'next/font/google';
import Navbar from '@/components/navbar/navbar';
import Hero from '@/components/hero/hero';
import Footer from '@/components/footer/footer';

const nunito_sans = Nunito_Sans({
  subsets: ['latin']
})

export const metadata = {
  title: 'I-Tech',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="id">
      <body className={nunito_sans.className}>
        <Navbar />
        <Hero />
        <main className='container'>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
