import './reset.css';
import './globals.css';
import { Nunito_Sans } from 'next/font/google'
import Navigation from './components/Navigation';

const nunito_sans = Nunito_Sans({
  subsets: ['latin']
})

export const metadata = {
  title: 'I-Tech',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="id">
      <body className={nunito_sans.className}>
        <Navigation></Navigation>
        {children}
      </body>
    </html>
  )
}
