export const metadata = {
  title: 'I-Tech: Kontak',
  description: 'Generated by create next app'
}

export default function Kontak() {
  return (
    <main >
      <div >
        <p>Kontak Page</p>
      </div>
    </main>
  )
}