export const metadata = {
  title: 'I-Tech: Akademik',
  description: 'Generated by create next app'
}

export default function Page() {
  return (
    <div >
      <div >
        <p>Akademik Page</p>
      </div>
    </div>
  )
}