export const metadata = {
  title: 'I-Tech: Akademik',
  description: 'Generated by create next app'
}

export default function Kontak() {
  return (
    <main >
      <div >
        <p>Akademik Page</p>
      </div>
    </main>
  )
}